version: 2

jobs:
  setup:
    working_directory: ~/Rise-Vision/widget-settings-ui-components
    shell: /bin/bash --login
    docker: &BUILDIMAGE
      - image: santiagoarriaga/cci-v2-widgets:0.0.1
    steps:
      - checkout
      - restore_cache:
         key: node-cache-y{{ checksum "package.json" }}
     - run: |
         echo $HOME
         echo $NVM_DIR
         ls ~/.nvm
         echo $PATH
         echo
      - run: |
          export PATH=/home/circleci/.nvm/versions/node/v4.2.2/bin:/usr/local/sbin:$PATH
          npm install
      - run: |
          export PATH=/home/circleci/.nvm/versions/node/v4.2.2/bin:/usr/local/sbin:$PATH
          echo $PATH
          bower install
      - save_cache:
         key: node-cache-y{{ checksum "package.json" }}
         paths:
           - ./node_modules
      - persist_to_workspace:
         root: .
         paths:
           - components

  test:
    working_directory: ~/Rise-Vision/widget-settings-ui-components
    shell: /bin/bash --login
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker: *BUILDIMAGE
    steps:
      - checkout
      - attach_workspace:
         at: .
      - restore_cache:
         key: node-cache-y{{ checksum "package.json" }}
      - run: wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
      - run: nohup bash -c "java -jar selenium-server-standalone-2.44.0.jar &"
      - run: git config --global user.email "jenkins@risevision.com"
      - run: git config --global user.name "jenkins-rise"
      - run: |
          export PATH=/home/circleci/.nvm/versions/node/v4.2.2/bin:/usr/local/sbin:$PATH
          NODE_ENV=prod XUNIT_FILE=$CIRCLE_TEST_REPORTS/angular-xunit.xml PROSHOT_DIR=$CIRCLE_TEST_REPORTS/screenshots ~/.nvm/versions/node/v4.2.2/bin/npm run test

  build:
    working_directory: ~/Rise-Vision/widget-settings-ui-components
    shell: /bin/bash --login
    docker: *BUILDIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-y{{ checksum "package.json" }}
      - run: |
          export PATH=/home/circleci/.nvm/versions/node/v4.2.2/bin:/usr/local/sbin:$PATH
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            NODE_ENV=prod npm run build
          else
            NODE_ENV=test npm run build
          fi

  build-demos:
    working_directory: ~/Rise-Vision/widget-settings-ui-components
    shell: /bin/bash --login
    docker: *BUILDIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-y{{ checksum "package.json" }}
      - run: |
          export PATH=/home/circleci/.nvm/versions/node/v4.2.2/bin:/usr/local/sbin:$PATH
          npm run ci-build-demo
      - run: |
          export PATH=/home/circleci/.nvm/versions/node/v4.2.2/bin:/usr/local/sbin:$PATH
          npm run ci-deploy-demo

workflows:
  version: 2
  workflow1:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - build-demos:
          requires:
            - build
          filters:
            branches:
              only:
                - master
